# Семинар NumPy

При выполнении заданий не используйте циклы и условные операторы. 
Внизу есть подсказки, какие функции можно/нужно использовать в некоторых из заданий, чтобы не тратить время на их поиск:)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

1. Создайте вектор, состоящий из нулей, длиной 10.

In [ ]:
import numpy as np

vector = np.zeros(10)
print(vector)

2. Создайте вектор, состоящий из нулей, длиной 10, где 4-ым элементом будет 1.

In [ ]:
import numpy as np

vector = np.full(10, 0)
vector[3] = 1
print(vector)

3. Создайте вектор длиной 10, заполненный числом 14,8.

In [ ]:
import numpy as np

vector = np.full(10, 14.8)
print(vector)

4. Создайте вектор со значениями от 23 до 38.

In [ ]:
import numpy as np

vector = np.arange(23, 39)
print(vector)

5. Переверните вектор (последнее значение становится первым и т.д.).

In [ ]:
import numpy as np

v = np.arange(10)
v = v[::-1]

print(v)

6. Из вектора длиной 9 создайте матрицу 3x3.

In [ ]:
import numpy as np

vector = np.arange(1, 10)
matrix = vector.reshape((3, 3))
print(matrix)

7. Создайте матрицу размерностью 3x3 и значениями от 0 до 8.

In [ ]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)

8. Найдите индексы ненулевых элементов в массиве `a`.


In [ ]:
import numpy as np

a = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(a)
print(non_zero_indices)

9. Создайте массив 10x10 со случайными значениями и найдите наименьшее и наибольшее значения в нём.

In [ ]:
import numpy as np

arr = np.random.randint(0, 100, size=(10, 10))

min_val = np.min(arr)
max_val = np.max(arr)

print("Минимальное значение:", min_val)
print("Максимальное значение:", max_val)

10. Создайте вектор длиной 15 со случайными значениями и найдите индексы, содержащие наименьшее и наибольшее значения.

In [ ]:
import numpy as np

vec = np.random.rand(15)

min_index = np.argmin(vec)
max_index = np.argmax(vec)

print("Вектор:", vec)
print("Индекс наименьшего значения:", min_index)
print("Индекс наибольшего значения:", max_index)

11. Создайте вектор со случайными значениями размерностью 30 и вычислите среднее значение.

In [ ]:
import numpy as np

vec = np.random.rand(30)

mean_val = np.mean(vec)

print("Среднее значение:", mean_val)

12. Создайте вектор со случайными значениями размерностью 3х10 и вычислите отдельно среднее значение в каждой строке (размерность итогового массива 3х1) и в каждом столбце (размерность итогового массива 10x1).

In [ ]:
import numpy as np

mat = np.random.rand(3, 10)

mean_row = np.mean(mat, axis=1)

mean_col = np.mean(mat, axis=0)

print("Средние значения по строкам:", mean_row)
print("Средние значения по столбцам:", mean_col)

13. Добавьте границы (состоящие из нулей) вокруг существующего массива. В итоге должен получиться массив такого вида:

``` 
00000
01110
01110
00000
 ```

In [ ]:
import numpy as np

mat = np.random.rand(3, 10)

mean_row = np.mean(mat, axis=1)

mean_col = np.mean(mat, axis=0)

mat_with_border = np.zeros((mat.shape[0]+2, mat.shape[1]+2))
mat_with_border[1:-1, 1:-1] = mat

print(mat_with_border)

14. Умножьте матрицу 5x3 на матрицу 3х2.

In [ ]:
import numpy as np

z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)

15. Найдите общие значения двух массивов (элементы в их пересечении).

In [ ]:
import numpy as np

arr1 = np.random.randint(0, 10, 10)
arr2 = np.random.randint(0, 10, 10)

common_values = np.intersect1d(arr1, arr2)

print("Массив 1:", arr1)
print("Массив 2:", arr2)
print("Общие значения:", common_values)

16. Создайте вектор со случайными значениями длиной 10 и отсортируйте его.

In [ ]:
import numpy as np

z = np.random.random(10)
z.sort()
print(z)

17. Создайте вектор со случайными значениями размерностью 10 и замените наибольшее значение нулём.

In [ ]:
import numpy as np

vec = np.random.rand(10)
max_val = np.max(vec)
vec[vec==max_val] = 0
print(vec)

18. Создайте матрицу 3х3 и “растяните” её в вектор (так, чтобы размерность стала 1х9) по крайней мере двумя способами.


In [ ]:
Первый способ:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = matrix.flatten()

print("Матрица:")
print(matrix)
print("Вектор:")
print(vector)

Второй способ:
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vector = matrix.reshape(1, -1)

print("Матрица:")
print(matrix)
print("Вектор:")
print(vector)


19. Создайте матрицу 4х4 и из каждой строки вычтите максимальное значение этой строки. Обратите внимание, что в полученной матрице в каждой строке одним из элементов должен быть 0.

Пример: из матрицы

```
[[0.60682249 0.7449185  0.03185808 0.15218245]
 [0.55140296 0.36923363 0.52486168 0.72297047]
 [0.63520354 0.54560057 0.9501767  0.05801644]
 [0.14608529 0.56327529 0.90571396 0.66212734]]
```
должна получиться матрица

```
[[-0.138096    0.         -0.71306042 -0.59273604]
 [-0.17156751 -0.35373684 -0.19810879  0.        ]
 [-0.31497315 -0.40457613  0.         -0.89216025]
 [-0.75962867 -0.34243867  0.         -0.24358662]]
```

***Подсказка***: при нахождении максимального элемента укажите аргумент `keepdims=True`.


In [ ]:
import numpy as np

mat = np.random.rand(4, 4)
max_vals = np.max(mat, axis=1, keepdims=True)
mat -= max_vals
print(mat)

20. Считайте массив из текстового файла (предварительно его создав, элементы массива - числа с плавающей точкой (float)) и совершите над ним какую-либо операцию.

Пример текста в файле:
`1.2 5.6 7.8`

In [ ]:
import numpy as np

arr = np.loadtxt('file.txt')
min_vals = np.min(arr, axis=1, keepdims=True)
arr -= min_vals
print(arr)



---

# Подсказки

1. zeros
3. full
4. arange
6. reshape
8. nonzero
9. Для создания массива со случайными значениями: np.random.random(shape), shape - размерность массива. Не забудьте, что если shape > 1, то размерности передаются в виде кортежа!
10. argmax, argmin
11. mean
13. pad
14. dot
15. Инициализировать массивы можно функцией np.random.randint() - в качестве аргументов передайте свои значения. Пересечение - intersect1d
16. sort
18. Один способ - flatten, другой уже использовался в предыдущих заданиях.
20. fromfile